### ADD COMMENT
POST http://localhost:8081/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkOTRjYzg5Ny01YmYwLTQ0MGQtOTdlOS1mZjgyMzY3NmViNDQiLCJpYXQiOjE3MzQzNjE3MTIsIm5iZiI6MTczNDM2MTcxMiwiZXhwIjoxNzM0NDQ4MTEyLCJzY29wZSI6WyJVU0VSIiwiQURNSU4iXSwiZW1haWwiOiJzaGU4MzU2OEBpbm9obS5jb20iLCJ1c2VybmFtZSI6Im5oc29uMjYxMiJ9.Oja2DdhIEs4QKgOjm4sZQNAvXW4bpP7pKOA6v8pMCRM
Content-Type: application/json

{
  "author": "nhson2612",
  "examId": "656220018643566592",
  "content": "Chánh Tổng Hoán ngay khi còn tại chức đã nổi tiếng là người khắc nghiệt",
  "createdAt": "",
  "lastUpdated": "",
  "deleted": false,
  "replies": []
}

### REPLY
POST http://localhost:8081/comment/reply/676077d14bc9f4348b2d775f
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkOTRjYzg5Ny01YmYwLTQ0MGQtOTdlOS1mZjgyMzY3NmViNDQiLCJpYXQiOjE3MzQzNjE3MTIsIm5iZiI6MTczNDM2MTcxMiwiZXhwIjoxNzM0NDQ4MTEyLCJzY29wZSI6WyJVU0VSIiwiQURNSU4iXSwiZW1haWwiOiJzaGU4MzU2OEBpbm9obS5jb20iLCJ1c2VybmFtZSI6Im5oc29uMjYxMiJ9.Oja2DdhIEs4QKgOjm4sZQNAvXW4bpP7pKOA6v8pMCRM
Content-Type: application/json

{
  "author": "nhson2612",
  "examId": "656220018643566592",
  "content": "Cái khắc nghiệt đến độ độc ác của ông thể hiện qua các hành vi diễn ra từng ngày",
  "createdAt": "",
  "lastUpdated": "",
  "deleted": false,
  "replies": []
}

### GET BY USER
GET http://localhost:8081/comment/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkOTRjYzg5Ny01YmYwLTQ0MGQtOTdlOS1mZjgyMzY3NmViNDQiLCJpYXQiOjE3MzQzNjE3MTIsIm5iZiI6MTczNDM2MTcxMiwiZXhwIjoxNzM0NDQ4MTEyLCJzY29wZSI6WyJVU0VSIiwiQURNSU4iXSwiZW1haWwiOiJzaGU4MzU2OEBpbm9obS5jb20iLCJ1c2VybmFtZSI6Im5oc29uMjYxMiJ9.Oja2DdhIEs4QKgOjm4sZQNAvXW4bpP7pKOA6v8pMCRM


### GET BY EXAM
GET http://localhost:8081/comment/exam/656220018643566592
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkOTRjYzg5Ny01YmYwLTQ0MGQtOTdlOS1mZjgyMzY3NmViNDQiLCJpYXQiOjE3MzQ0NTI5ODIsIm5iZiI6MTczNDQ1Mjk4MiwiZXhwIjoxNzM0NTM5MzgyLCJzY29wZSI6WyJVU0VSIiwiQURNSU4iXSwiZW1haWwiOiJzaGU4MzU2OEBpbm9obS5jb20iLCJ1c2VybmFtZSI6Im5oc29uMjYxMiJ9.LH1gj0iXprQfEtt3YdZHe2U7c2fLJDIEBV6QzJqmXJg