### CREATE AN EXAM
POST localhost:8081/exams/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NTA2Njk5NjE4Nzc5MTM2MDAiLCJpYXQiOjE3MzI5ODI3ODUsIm5iZiI6MTczMjk4Mjc4NSwiZXhwIjoxNzMzMDY5MTg1LCJzY29wZSI6WyJVU0VSIl0sImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6InNub3dmbGFrZS10ZXN0In0.PSt4eXF0TffEKT4QJXfOkFFq7s47d_Iquwl6NUNaXM0

{
  "id": "",
  "name": "Bài kiểm tra số 2",
  "subject": "MATH",
  "duration": 60,
  "provider": "",
  "numberOfQuestion": 10,
  "difficultyLevel": "EASY",
  "maxAttempts": 3,
  "classId": "650729669565382656"
}

### ACTIVATE AN EXAM
PUT http://localhost:8081/exams/activate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NTA2Njk5NjE4Nzc5MTM2MDAiLCJpYXQiOjE3MzI5ODI3ODUsIm5iZiI6MTczMjk4Mjc4NSwiZXhwIjoxNzMzMDY5MTg1LCJzY29wZSI6WyJVU0VSIl0sImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6InNub3dmbGFrZS10ZXN0In0.PSt4eXF0TffEKT4QJXfOkFFq7s47d_Iquwl6NUNaXM0

[
  {
    "examId": "exam_1",
    "name": "Bài kiểm tra số",
    "classId": null,
    "subject": "MATH",
    "duration": 60,
    "provider": "Teacher 1",
    "numberOfQuestion": 10,
    "difficultyLevel": "EASY",
    "createdDate": "2024-11-22T01:10:31.8966149",
    "lastUpdatedDate": null,
    "maxAttempts": 3,
    "status": "NOT_ACCEPTED",
    "type": "PUBLIC",
    "id": "exam_1",
    "new": false
  }
]


### DELETE AN EXAM
DELETE http://localhost:8081/exams/delete/f6c13ae9-b503-46df-86f2-d943c842bf02
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkOTRjYzg5Ny01YmYwLTQ0MGQtOTdlOS1mZjgyMzY3NmViNDQiLCJpYXQiOjE3MzM3NzQ5NjQsIm5iZiI6MTczMzc3NDk2NCwiZXhwIjoxNzMzODYxMzY0LCJzY29wZSI6WyJVU0VSIiwiQURNSU4iXSwiZW1haWwiOiJzaGU4MzU2OEBpbm9obS5jb20iLCJ1c2VybmFtZSI6Im5oc29uMjYxMiJ9.X6X0uKLBal5tvtIM_jqYXWRkHGPdIwilKNMHp7CBGOs


### GET EXAMS BY USER
GET http://localhost:8081/exams/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkOTRjYzg5Ny01YmYwLTQ0MGQtOTdlOS1mZjgyMzY3NmViNDQiLCJpYXQiOjE3MzQzNjE3MTIsIm5iZiI6MTczNDM2MTcxMiwiZXhwIjoxNzM0NDQ4MTEyLCJzY29wZSI6WyJVU0VSIiwiQURNSU4iXSwiZW1haWwiOiJzaGU4MzU2OEBpbm9obS5jb20iLCJ1c2VybmFtZSI6Im5oc29uMjYxMiJ9.Oja2DdhIEs4QKgOjm4sZQNAvXW4bpP7pKOA6v8pMCRM

