GET http://localhost:8080/exams?subject=Math&limit=1&lastExam=2023-07-21T15:30:00

###
#GET http://localhost:8081/exams?limit=10&lastExam=2024-12-29T15:30:00
GET http://localhost:8081/exams?limit=10&lastExam=2024-11-28T11:46:55.454
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkOTRjYzg5Ny01YmYwLTQ0MGQtOTdlOS1mZjgyMzY3NmViNDQiLCJpYXQiOjE3MzM5MzQ3MDQsIm5iZiI6MTczMzkzNDcwNCwiZXhwIjoxNzM0MDIxMTA0LCJzY29wZSI6WyJVU0VSIiwiQURNSU4iXSwiZW1haWwiOiJzaGU4MzU2OEBpbm9obS5jb20iLCJ1c2VybmFtZSI6Im5oc29uMjYxMiJ9.t5E67EHwFMEtIaNVz4e87eE-haFI8H_lGMYY1BPCIv4



###
GET http://localhost:8081/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDMzMjQ1MzQwNDM2NDMyMDQ4OTMiLCJpYXQiOjE3MzIwMzU2MzAsIm5iZiI6MTczMjAzNTYzMCwiZXhwIjoxNzMyMTIyMDMwLCJpc3MiOiJBdXRoU2VydmljZSIsInNjb3BlIjpbImdvb2dsZWFwaXMuYXV0aC51c2VyaW5mby5lbWFpbCIsIm9wZW5pZCIsImdvb2dsZWFwaXMuYXV0aC51c2VyaW5mby5wcm9maWxlIiwiVVNFUiJdLCJlbWFpbCI6Im5oc29uMjYxMjIwMDRAZ21haWwuY29tIn0.c5_3-WuIdMO_7x7PemIqFEbo9g_BNGmgqEqr8ZaX-vo
