### GET PROFILE
GET http://localhost:8083/profile/650669961877913600
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0ZTA4N2U3Ny0wNDVjLTQ1YWItYjViNC1iZjkyYmMxY2MyM2IiLCJpYXQiOjE3MzQzMzg0MzQsIm5iZiI6MTczNDMzODQzNCwiZXhwIjoxNzM0NDI0ODM0LCJzY29wZSI6WyJVU0VSIl0sImVtYWlsIjoidGVzdDFAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6Im5oaGlldTI2MTIifQ.aX09isDCtrf10lDOFyjf2Ho7Mwx_P2mwoTKmz25Pmw0

### GET statistics
GET http://localhost:8083/profile/statistics
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkOTRjYzg5Ny01YmYwLTQ0MGQtOTdlOS1mZjgyMzY3NmViNDQiLCJpYXQiOjE3MzQ0NTI5ODIsIm5iZiI6MTczNDQ1Mjk4MiwiZXhwIjoxNzM0NTM5MzgyLCJzY29wZSI6WyJVU0VSIiwiQURNSU4iXSwiZW1haWwiOiJzaGU4MzU2OEBpbm9obS5jb20iLCJ1c2VybmFtZSI6Im5oc29uMjYxMiJ9.LH1gj0iXprQfEtt3YdZHe2U7c2fLJDIEBV6QzJqmXJg