### CREATE A CLASS
POST http://localhost:8088/class/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NTA2Njk5NjE4Nzc5MTM2MDAiLCJpYXQiOjE3MzI5ODI3ODUsIm5iZiI6MTczMjk4Mjc4NSwiZXhwIjoxNzMzMDY5MTg1LCJzY29wZSI6WyJVU0VSIl0sImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6InNub3dmbGFrZS10ZXN0In0.PSt4eXF0TffEKT4QJXfOkFFq7s47d_Iquwl6NUNaXM0

{
  "className": "Lớp A Chính",
  "description": "Lớp học vật lý của A Chính",
  "teacherName": "A Chính"
}


### GET INVITE LINK
GET http://localhost:8088/class/invite-link?class-id=650769624643698688
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0ZTA4N2U3Ny0wNDVjLTQ1YWItYjViNC1iZjkyYmMxY2MyM2IiLCJpYXQiOjE3MzI5ODYyNzMsIm5iZiI6MTczMjk4NjI3MywiZXhwIjoxNzMzMDcyNjczLCJzY29wZSI6WyJVU0VSIl0sImVtYWlsIjoidGVzdDFAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6Im5oaGlldTI2MTIifQ.MZUmqBJFYGpXF0XgP60Ltoc13n2NGmDYfqVOC2wVmsg


### JOIN A CLASS
GET http://localhost:8088/class?invite-token=a2LY1jiV63UKEyZVPyy%2BsdK1eTh6%2BNLgwYQcNdpFTdA%3D&username=NHSON
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkOTRjYzg5Ny01YmYwLTQ0MGQtOTdlOS1mZjgyMzY3NmViNDQiLCJpYXQiOjE3MzMzMzExNDMsIm5iZiI6MTczMzMzMTE0MywiZXhwIjoxNzMzNDE3NTQzLCJzY29wZSI6WyJVU0VSIiwiQURNSU4iXSwiZW1haWwiOiJzaGU4MzU2OEBpbm9obS5jb20iLCJ1c2VybmFtZSI6Im5oc29uMjYxMiJ9.aEW6XQe37xikx9R8VHSIsyVx8prkPgsTXFxeCv6VEf8


### DELETE CLASS
DELETE http://localhost:8088/class/123
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NTA2Njk5NjE4Nzc5MTM2MDAiLCJpYXQiOjE3MzM3NzEwNDUsIm5iZiI6MTczMzc3MTA0NSwiZXhwIjoxNzMzODU3NDQ1LCJzY29wZSI6WyJVU0VSIl0sImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6InNub3dmbGFrZS10ZXN0In0.cWkOKN3tdznSnIn3sugHrES9-Q2jZw237v3Ff3LAA08


### GET A CLASS
GET http://localhost:8088/class/650729669565382656
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkOTRjYzg5Ny01YmYwLTQ0MGQtOTdlOS1mZjgyMzY3NmViNDQiLCJpYXQiOjE3MzI5ODgyNzYsIm5iZiI6MTczMjk4ODI3NiwiZXhwIjoxNzMzMDc0Njc2LCJzY29wZSI6WyJVU0VSIiwiQURNSU4iXSwiZW1haWwiOiJzaGU4MzU2OEBpbm9obS5jb20iLCJ1c2VybmFtZSI6Im5oc29uMjYxMiJ9.qvWR5qwFdiYGtyZIXi5HvVpDNcXFsxwIVqWR5iY0EtA

### GET ALL CLASS
GET http://localhost:8088/class
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0ZTA4N2U3Ny0wNDVjLTQ1YWItYjViNC1iZjkyYmMxY2MyM2IiLCJpYXQiOjE3MzI5ODYyNzMsIm5iZiI6MTczMjk4NjI3MywiZXhwIjoxNzMzMDcyNjczLCJzY29wZSI6WyJVU0VSIl0sImVtYWlsIjoidGVzdDFAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6Im5oaGlldTI2MTIifQ.MZUmqBJFYGpXF0XgP60Ltoc13n2NGmDYfqVOC2wVmsg


### GET CLASS
GET http://localhost:8088/class/1ac59a98-3363-4d51-bda3-be983ce64c01
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkOTRjYzg5Ny01YmYwLTQ0MGQtOTdlOS1mZjgyMzY3NmViNDQiLCJpYXQiOjE3MzIxODQ5NzMsIm5iZiI6MTczMjE4NDk3MywiZXhwIjoxNzMyMjcxMzczLCJpc3MiOiJBdXRoU2VydmljZSIsInBlcm1pc3Npb25zIjpbXSwic2NvcGUiOlsiVVNFUiJdLCJlbWFpbCI6Im5oc29uMjYxMkBleGFtcGxlLmNvbSJ9._acxoyxI8jsf-jeyb842po0HaTgutLdocsZ4cQzO194


### ADD ANNOUNCEMENT
POST http://localhost:8088/class/664374233169690624/announcement
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NTA2Njk5NjE4Nzc5MTM2MDAiLCJpYXQiOjE3MzY1Mjg1MDgsIm5iZiI6MTczNjUyODUwOCwiZXhwIjoxNzM2NjE0OTA4LCJzY29wZSI6WyJVU0VSIl0sImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6InNub3dmbGFrZS10ZXN0In0.YnWJoExABFP6Zjg47mcTa4HSIc4z4N-QrN0UEzmzztE
Content-Type: application/json

{
  "announcementId": "unique-announcement-id",
  "title": "Class Update",
  "content": "This is a content for the class announcement.",
  "date": "2025-01-11T10:30:00",
  "type": "GENERAL",
  "clazz": {
    "classId": ""
  }
}


### ADD MATERIAL
POST http://localhost:8088/class/664374233169690624/material
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NTA2Njk5NjE4Nzc5MTM2MDAiLCJpYXQiOjE3MzY1Mjg1MDgsIm5iZiI6MTczNjUyODUwOCwiZXhwIjoxNzM2NjE0OTA4LCJzY29wZSI6WyJVU0VSIl0sImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6InNub3dmbGFrZS10ZXN0In0.YnWJoExABFP6Zjg47mcTa4HSIc4z4N-QrN0UEzmzztE
Content-Type: application/json

{
  "materialId": "",
  "title": "Sample Material 2 Title",
  "url": "https://fontawesome.com/v4/icons/",
  "aClass": {
    "classId": ""
  }
}
